version: '3.8'

services:
  # [서버 1] OCL 인스턴스 A 시뮬레이션
  chat-app-1:
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  # [서버 2] OCL 인스턴스 B 시뮬레이션
  chat-app-2:
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  # [로드 밸런서] OCL Load Balancer 시뮬레이션
  nginx:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
