jwt:
  secret: ${JWT_SECRET_KEY}

spring:
  profiles:
    active: local
  
  session:
    store-type: redis
    redis:
      namespace: spring:session
      flush-mode: on_save

  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD:}

    mongodb:
      host: localhost
      port: 27016
      database: chat

    datasource:
      hikari:
        maximum-pool-size: 15
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3307/chat?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: root
      password: ${DB_PASSWORD:1234}

  # DDL 추출을 위해 Flyway를 끄고, ddl-auto를 create로 변경
  flyway:
    enabled: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update # create로 변경
    show-sql: true # jpa 하위가 아닌 spring.jpa의 속성으로 변경
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
        default_batch_fetch_size: 10

cors:
  allowed-origins: "*"

snowflake:
  node-id: 1

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info, metrics
  metrics:
    enable:
      hikaricp: true
  endpoint:
    prometheus:
      enabled: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
